dataSource:
#  type: mongo
#  url: "mongodb://localhost:27017/myFirstMongDb"
#  schema: myFirstMongDb
#  port: 27017

  type: mysql
  host: "localhost"
  port: 3306
  username: root
  password: 12345678
  schema: 'hms'

log:
  level: "info"
  size: 10
  backups: 5
  path: "log/app.log"
  age: 7