app:
  port: 14083
  env: "development"
  app_name: "xuanyuan"
  app_url: "xuanyuan.com.cn"
dataSource:
#  type: mongo
#  url: "mongodb://localhost:27017/myFirstMongDb"
#  schema: myFirstMongDb
#  port: 27017

  driver: mysql
  host: "localhost"
  port: 3306
  username: root
  password: 12345678
  schema: 'hms'
  max_idle_conns: 10 # 空闲连接池中最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info  # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称
  charset: utf8mb4

log:
  level: "info"
  size: 10
  backups: 5
  age: 7
  rootdir: "/Users/haoguosheng/GolandProjects/xuanyuan/logs"
  filename: "app.log"
  compress: true

redis:
  host: "localhost"
  port: 6379
  password: "lxnrav2"
  db: 0

jwt:
  secret: "3Bde3BGEbYqtqyEUzW3ry8jKFcaPH17fRmTmqE7MDr05Lwj95uruRKrrkb44TJ4s"
  jwt_ttl: 43200
  jwt_blacklist_grace_period: 10
  refresh_grace_period: 1800